version: 0.2

phases:
  install:
    commands:
      
      
      - echo Installing Yarn...
      
      
  pre_build:
    commands:
      - echo Installing dependencies...
    
  build:
    commands:
      - echo Testing...
    
      
artifacts:
  files:
    - "package.json"
  discard-paths: no
  base-directory: dist
