version: 0.2

phases:
  install:
    commands:
      
      
      - echo Installing Yarn...
      - yarn install --production
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Testing...
      - yarn test
      
artifacts:
  files:
    - "package.json"
  discard-paths: no
  base-directory: dist
